server:
  port: 6060
spring:
  application:
    name: tableshare_server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tableShare
    username: root
    password: Gaine#0628
    hikari:
      max-lifetime: 59000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
jwt:
  haeder: Authorization
  secret: 77+977+977+977+977+9JFEiR++/vXfvv73vv73erVvvv71zSO+/vXLVu++/ve+/ve+/vXPvv71o77+9Ku+/ve+/vXTvv70k77+9Z++/vXpETTQlezPvv714N++/vVki77+977+9JQ==
  token-expires-time: 3600000000000000000
google:
  maps-api-key: AIzaSyCnbvtDeLHfYN_48GE2EY4Gd78uPB3QOWM
  maps-api-password: 8OIp-Uu3VlM_2mdWH93V7MLpL2w=
cloud:  # todo make a bucket
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: nonabili-bucket
      accessKey: AKIAW3BEXVIAZHCYSIFL
      secretKey: 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